--- 
org: 
  cloudfoundry: 
    demo: 
      people: 
        zipkin: 
          enabled: false
spring: 
  application: 
    name: people
  sleuth: 
    sampler: 
      percentage: 1.0
  jpa:
    hibernate:
      ddl-auto: update
     
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: eureka
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80