--- 
org: 
  cloudfoundry: 
    demo: 
      people: 
        zipkin: 
          enabled: false
spring: 
  application: 
    name: people
  sleuth: 
    sampler: 
      percentage: 1.0
  jpa:
    hibernate:
      ddl-auto: update